lib/phoenix_course_web/router.ex
defmodule PhoenixCourseWeb.Router do
  use PhoenixCourseWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug PhoenixCourse.GuardianPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", PhoenixCourseWeb do
    pipe_through [:browser, :auth]
    get "/login", AuthController, :new
    post "/login", AuthController, :login
    get "/sign-in", UserController, :new
    post "/sign-in", UserController, :create
  end

  scope "/", PhoenixCourseWeb do
    pipe_through [:browser, :auth, :ensure_auth]
    get "/", PageController, :index
    resources "/categories", CategoryController
    resources "/products", ProductController
    resources "/orders", OrderController
    post "/logout", AuthController, :logout
  end

  scope "/api", PhoenixCourseWeb.Api do
    pipe_through :api
    post "/login", AuthController, :login
  end

  scope "/api", PhoenixCourseWeb.Api do
    pipe_through [:api, :auth, :ensure_auth]
    get "/profile", AuthController, :profile
  end
end

lib/phoenix_course_web/views/layout_view.ex
defmodule PhoenixCourseWeb.LayoutView do
  use PhoenixCourseWeb, :view

  def active_link(conn, controllers) when is_list(controllers) do
    if Enum.member?(controllers, Phoenix.Controller.controller_module(conn)) do
      "active"
    else
      ""
    end
  end

  def active_link(conn, controller) do
    active_link(conn, [controller])
  end
end

lib/phoenix_course_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <%= render(PhoenixCourseWeb.LayoutView, "head.html", conn: @conn) %>
  </head>
  <body class="d-flex flex-column h-100" cz-shortcut-listen="true">
    <%= render(PhoenixCourseWeb.LayoutView, "header.html", conn: @conn) %>
    <main role="main" class="flex-shrink-0">
      <div class="container pt-5 mt-5">
         <%= if get_flash(@conn, :info)  != nil do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error)  != nil do %>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <% end %>
          <%= render @view_module, @view_template, assigns %>
      </div>
    </main>
    <%= render(PhoenixCourseWeb.LayoutView, "footer.html", conn: @conn) %>
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js") %>'></script>
  </body>
</html>

lib/phoenix_course_web/templates/layout/auth.html.eex
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    <%= render(PhoenixCourseWeb.LayoutView, "head.html", conn: @conn) %>
  </head>
  <body class="d-flex flex-column h-100" cz-shortcut-listen="true">
    <main role="main" class="flex-shrink-0">
      <div class="container pt-5">
         <%= if get_flash(@conn, :info)  != nil do %>
            <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
          <% end %>
          <%= if get_flash(@conn, :error)  != nil do %>
            <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
          <% end %>
          <%= render @view_module, @view_template, assigns %>
      </div>
    </main>    
    <script type="text/javascript" src='<%= Routes.static_path(@conn, "/js/app.js") %>'></script>
  </body>
</html>

lib/phoenix_course_web/templates/layout/footer.html.eex
<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Phoenix Course - Quanterall</span>
  </div>
</footer>

lib/phoenix_course_web/templates/layout/head.html.eex
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>PhoenixCourse · Quanterall</title>
<link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>

lib/phoenix_course_web/templates/layout/header.html.eex
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">Phoenix Course</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= active_link(@conn,PhoenixCourseWeb.PageController)%>">
          <%= link("Home", to: Routes.page_path(@conn, :index), class: "nav-link") %>
        </li>
        <li class="nav-item <%= active_link(@conn,PhoenixCourseWeb.CategoryController)%>">
          <%= link("Categories", to: Routes.category_path(@conn, :index), class: "nav-link") %>
        </li>
        <li class="nav-item <%= active_link(@conn,PhoenixCourseWeb.ProductController)%>">
          <%= link("Products", to: Routes.product_path(@conn, :index), class: "nav-link") %>
        </li>
        <li class="nav-item <%= active_link(@conn,PhoenixCourseWeb.OrderController)%>">
          <%= link("Orders", to: Routes.order_path(@conn, :index), class: "nav-link") %>
        </li>
      </ul>
      <%= form_for @conn, Routes.auth_path(@conn, :logout), [class: "form-inline mt-2 mt-md-0"] ,fn _ -> %>
        <%= submit "Logout", class: "btn btn-outline-primary border-0 my-2 my-sm-0" %>
      <% end %>
    </div>
  </nav>
</header>